import type { ItemDefinition } from '../../types.js';

export const NATIVE_ITEMS: Readonly<Record<string, ItemDefinition>> = {
  woven_bag: {
    id: 'woven_bag',
    version: 1,
    portable: true,
    packingLoad: 2,
    name: 'Woven bag',
    description:
      'A portable woven bag with 24 packing-load units of capacity. Nested contents count toward the limit.',
    properties: ['fiber', 'pouch'],
    container: { capacity: 24, maximumDepth: 16 },
  },
  raw_fiber: {
    id: 'raw_fiber',
    version: 1,
    portable: true,
    packingLoad: 1,
    name: 'Reed fibers',
    description: 'Unprepared plant fibers stripped from reeds.',
    properties: ['fiber'],
  },
  prepared_fiber: {
    id: 'prepared_fiber',
    version: 1,
    portable: true,
    packingLoad: 1,
    name: 'Prepared fibers',
    description: 'Cleaned flexible fibers, suitable for weaving a pouch or fletching.',
    properties: ['fiber', 'flexible', 'pouch'],
  },
  cord: {
    id: 'cord',
    version: 1,
    portable: true,
    packingLoad: 1,
    name: 'Fiber cord',
    description: 'Twisted fibers suitable for fastening and transmitting tension.',
    properties: ['binding', 'flexible'],
  },
  wood: {
    id: 'wood',
    version: 1,
    portable: true,
    packingLoad: 1,
    name: 'Supple branch',
    description: 'A workable branch: rigid as a short shaft, flexible over its length.',
    properties: ['rigid', 'flexible', 'shaft', 'fuel'],
  },
  stone: {
    id: 'stone',
    version: 1,
    portable: true,
    packingLoad: 1,
    name: 'Small stone',
    description: 'A rounded stone that can serve as sling ammunition.',
    properties: ['rigid', 'projectile'],
    ammunition: { kind: 'stone', damageBonus: 0 },
  },
  bone: {
    id: 'bone',
    version: 1,
    portable: true,
    packingLoad: 1,
    name: 'Bone fragment',
    description: 'A workable hard fragment suitable for a simple point.',
    properties: ['rigid', 'point'],
  },
  stone_tool: {
    id: 'stone_tool',
    version: 1,
    portable: true,
    packingLoad: 1,
    name: 'Flaked cutting stone',
    description: 'A modest existing possession, used to prepare animal remains.',
    properties: ['rigid', 'point'],
  },
  berries: {
    id: 'berries',
    version: 1,
    portable: true,
    packingLoad: 1,
    name: 'Wild berries',
    description: 'Familiar edible berries.',
    properties: ['food'],
    nutrition: 18,
  },
  raw_meat: {
    id: 'raw_meat',
    version: 1,
    portable: true,
    packingLoad: 1,
    name: 'Raw meat',
    description: 'Fresh meat. Cook it at a lit campfire before eating.',
    properties: ['food'],
    cooked: false,
  },
  cooked_meat: {
    id: 'cooked_meat',
    version: 1,
    portable: true,
    packingLoad: 1,
    name: 'Cooked meat',
    description: 'Meat cooked through over a dependable fire.',
    properties: ['food'],
    nutrition: 38,
    cooked: true,
  },
};

export const NATIVE_PREPARATIONS = {
  fiber: {
    input: 'raw_fiber',
    inputQuantity: 2,
    output: 'prepared_fiber',
    outputQuantity: 2,
    workSeconds: 48,
  },
  cord: {
    input: 'prepared_fiber',
    inputQuantity: 2,
    output: 'cord',
    outputQuantity: 1,
    workSeconds: 60,
  },
} as const;
