import fs from 'node:fs';
import { createHash } from 'node:crypto';
import { performance } from 'node:perf_hooks';
import * as D from '../packages/domain/src/index.ts';
import { advanceNativeStep } from '../apps/server/src/native-step.ts';
const cases=[];
const fixture=()=>{const w=D.createWorld(73);D.migrateCognition(w);const base=w.entities[D.PLAYER_ID];for(let i=0;i<500;i++)w.entities[`burst-object-${i}`]={id:`burst-object-${i}`,name:`Fixture object ${i}`,kind:'resource',position:{...base.position,x:base.position.x+1+(i%3)*.2},spatial:structuredClone(base.spatial),resource:{definitionId:'stone',quantity:1,workSeconds:1}};return D.freezeWorld(w);};
const hash=x=>createHash('sha256').update(JSON.stringify(x)).digest('hex');
let source=fixture();const original=hash(source);
const synchronous=D.advanceWorld(source,1);
let ticks=0;const pulse=setInterval(()=>ticks++,1);
const start=performance.now();const cooperative=await advanceNativeStep(source);clearInterval(pulse);
if(hash(cooperative.transition)!==hash(synchronous))throw Error('Cooperative transition diverged');
if(hash(source)!==original)throw Error('Source changed');
cases.push({name:'cooperative-cold-step',elapsedMs:performance.now()-start,cpuMs:cooperative.cpuMs,maxSliceMs:cooperative.maxSliceMs,yields:cooperative.yields,timerCallbacks:ticks,fullTransitionEqual:true,inputUnchanged:true,events:cooperative.transition.events.length});
source=D.freezeWorld(cooperative.transition.world);
const continued=await advanceNativeStep(source);
if(hash(continued.transition)!==hash(D.advanceWorld(source,1)))throw Error('Warm transition diverged');
cases.push({name:'cooperative-warm-step',cpuMs:continued.cpuMs,yields:continued.yields,fullTransitionEqual:true});
const invalid=D.advanceWorld(source,-1), invalidWork=D.advanceWorldWork(source,-1).next();
if(!invalidWork.done||hash(invalid)!==hash(invalidWork.value))throw Error('Invalid duration mismatch');
const report={scope:'Ad hoc synchronous/cooperative native runtime, no automated suite or live models.',node:process.version,run:process.env.GITHUB_RUN_ID,paidModelCalls:0,cases};
fs.writeFileSync('docs/verification/perception-cooperative.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2));
