from pathlib import Path
import os, re, hashlib, json
root = Path(os.environ['REVIEW_ROOT'])
changed = set()
def replace(path, old, new):
    p = root/path; s = p.read_text()
    if old not in s: raise RuntimeError('Missing text in '+path+': '+old[:80])
    p.write_text(s.replace(old,new)); changed.add(path)
def paragraph(path, start, text):
    p=root/path; s=p.read_text(); matches=[x for x in (s.splitlines() if start.startswith('- ') else s.split('\n\n')) if x.startswith(start)]
    if len(matches)!=1: raise RuntimeError('Ambiguous paragraph '+path+': '+start)
    p.write_text(s.replace(matches[0],text)); changed.add(path)
def append(path, text):
    p=root/path; p.write_text(p.read_text().rstrip()+'\n\n'+text.strip()+'\n'); changed.add(path)
def after_title(path,text):
    p=root/path; s=p.read_text(); a,b=s.split('\n',1);p.write_text(a+'\n\n'+text.strip()+'\n'+b); changed.add(path)

paragraph('docs/architecture.md','The application processes fixed one-simulation-second steps,', '''The application advances boundary-limited elapsed intervals, not one transition per game second. The existing 50 ms host wake admits time debt; routine durability remains coalesced to one real second and commands/control changes commit immediately. Clean shutdown flushes pending progress; an abrupt crash can lose only the already documented unflushed routine progress. Each call reconciles due start-state decisions and status/action transitions, captures active rates, forecasts a bounded interval, integrates that elapsed time, then commits completions and perception before reconsidering. New work receives no preceding time. `temporal-boundaries.ts` composes the current finite families; `simulation-time.ts` supplies shared rate/condition calculations. The base-world [time policy](worlds/base/time.md) owns fidelity and fallback values; [simulation time](simulation-time.md) owns the contract.

The host subtracts actual `simTime` progress, not requested steps, and yields mutation ownership between approximately eight-millisecond batches. One atomic interval can exceed that soft budget. The base conversion remains sixty game seconds per wall second at 1x; speed increases owed time, not an update count. Navigation preparation, genuine suspension and explicit pause remain separately accounted. Speed changes retain admitted debt; explicit pause/suspension follow their existing reset policy. Rendering and camera input remain device-paced; a possible twenty-Hz pose publication policy is not a twenty-FPS rendering limit.

Domain transitions use isolated Immer drafts with unchanged branches shared. The server freezes loaded/migrated state, accepted command/editor snapshots and native interval results, skipping already-frozen branches. Builders remain mutable until server handoff; auto-freezing remains disabled. Domain callers must not mutate returned snapshots. Selected rates, phase-local IDs and working-action identity are captured before integration. This is not a general event scheduler: one global minimum interval still couples dense local activity to unrelated participants, sensing uses a documented displacement bound, and arbitrary coupled/clamped rules retain a conservative fallback. [PF13](maintainers/performance.md#pf13--elapsed-time-simulation) distinguishes delivery from extreme-scale qualification.''')
replace('docs/architecture.md','after preparation the normal fixed-step order resumes','after preparation the normal native-interval phase order resumes')
replace('docs/architecture.md','pure commands and fixed steps','pure commands and elapsed intervals')
replace('docs/architecture.md','One ready step starts per actor per fixed step, after native emergency handling.','One ready plan step may start per actor at a native interval boundary, after emergency handling; it receives no work from before its start.')
paragraph('packages/domain/src/README.md','- `advanceWorld(world, seconds)`:', '- `advanceWorld(world, seconds, { maxIntervals })`: advances a bounded prefix of elapsed game time without AI. The caller subtracts actual `simTime` progress, not calls or requested seconds. Paused/navigation-blocked worlds do not advance. Due start transitions, captured rates, endpoint effects and sampled perception follow [simulation time](../../../docs/simulation-time.md); host presence, speed and budgets remain application responsibilities.')
replace('archive/07-technical-architecture/spatial-world-runtime.md','Pause before the next fixed step','Pause before the next native interval')
replace('archive/07-technical-architecture/spatial-world-runtime.md','Resume ordinary fixed-step ordering once data is ready.','Resume the [elapsed-interval phase contract](../../docs/simulation-time.md) once data is ready.')
replace('archive/07-technical-architecture/spatial-world-runtime.md','native fixed-step movement','native elapsed movement')
replace('archive/07-technical-architecture/spatial-world-runtime.md','Respect the existing fixed-step order and time-debt policy; do not introduce a second simulation clock.','Respect start/end interval ownership and actual-progress debt accounting in [simulation time](../../docs/simulation-time.md); do not introduce a second simulation clock.')
paragraph('docs/performance.md','Preserve one-second native semantics,', '''[Simulation time](simulation-time.md) owns the elapsed-integration contract. Compile participant IDs outside drafts and reuse them until a membership/component-changing command invalidates that roster; retain IDs rather than draft entities. The current finite native families capture active rates/work at the start and integrate to a relevant mechanical or authored fidelity boundary, instead of traversing the world once per game second. Status applicability and immutable static-object exposure reuse remove unrelated work. Ordering, saved randomness, real collision and source-scoped evidence remain protected, but the obsolete one-second trace is not itself a gameplay requirement. The [base time policy](worlds/base/time.md) states sampling/approximation limits and coupled-rule fallbacks.''')
paragraph('docs/performance.md','- Finalize a bounded set of fixed steps once', '- Bound finalization and work using the existing elapsed-interval owner. Do not merely pass a larger duration into a legacy per-second implementation: active rates, starts/completions, consequences, observation fidelity and RNG ordering need explicit contracts. PF13 delivers the current finite families; arbitrary coupled mechanics and regional schedules remain gated.')
paragraph('docs/performance.md','Native throughput must cover 60 one-second transitions', '''Measure actual game-time progress divided by real elapsed time against `baseRatio × speed`, with headroom for commands, persistence and publication. There is no sixty/480-transition requirement. Count actual completed intervals, their game durations and CPU cost separately; a short deadline can still dominate a global scheduler. Preserve immutable snapshot sharing, append lineage and privacy invalidation. Measure initial exposure/freezing and mature-state growth, not only short pre-frozen runs.''')
paragraph('docs/performance.md','Action acceptance and first visible movement are different milestones.', '''Action acceptance and first visible movement are different milestones. The current fifty-millisecond host wake admits elapsed time and publishes scoped progress without imposing that rate on rendering. Retain one-real-second routine durability and immediate consequential/authorization boundaries. Future pose coalescing must preserve reliable events and cannot advance unowed time. Device-paced interpolation and prediction are separate presentation/network choices, not simulation tick requirements.''')
paragraph('docs/performance.md','The current host has a base ratio of 60 simulated seconds', '''The base conversion is sixty game seconds per real second: speed eight requests 480 game seconds of progress, **not 480 mandatory native transitions**. Use [the elapsed-interval contract](simulation-time.md), not the superseded 2.08 ms per-one-second-step assumption. The host retains an approximately eight-millisecond cooperative work budget, while a single atomic interval may exceed it. Measure actual achieved clock rate, interval count/duration, work per affected entity, command latency and debt together. Rendering targets display cadence independently; no twenty-FPS cap follows from sparse updates.''')
replace('docs/performance.md','or replace several fixed steps with a single coarse step to meet the target','or jump over unhandled consequential boundaries to meet the target')
replace('docs/performance.md','fixed-step yielding and trigger-based background work','elapsed-prefix yielding and trigger-based background work')
paragraph('docs/performance.md','Move genuinely cold historical data off repeated', '''Move genuinely cold historical data off repeated finalization/serialization paths under PF08 while retaining evidence, stable IDs, pending commitments, current knowledge and explicit durable reads. PF13 already integrates selected finite rates to their next bound; it does not certify arbitrary nonlinear or coupled authored rules. Use the [running boundary catalogue](maintainers/simulation-boundaries.md) to identify further independent deadlines, valid bounds and invalidators before adding regional schedules or a general event heap. Do not discard meaningful interactions to make a latency target pass.''')
replace('docs/maintainers/performance.md','preserve one writer and fixed-step order','preserve one writer and native phase order')
paragraph('docs/maintainers/performance.md','- [ ] Verify backlog backpressure stops simulation growth', '- [ ] Qualify nonblocking memory pressure with recent/protected evidence, failed or unavailable maintenance and mature histories. Preserve sources and allow native time/movement; real storage errors still pause admission. Failed unchanged maintenance must not retry automatically. Profile retained-history traversal before increasing workload claims. This supersedes the obsolete request to stop simulation on optional memory backlog.')
paragraph('docs/maintainers/performance.md','- [ ] **PF12.3 /', '- [ ] **PF12.3 / PF09 / EPR02–03** Complete dirty region/target updates and broader static-exposure qualification. The immutable static-object exposure helper and unchanged episode reuse are delivered within PF13; do not reimplement them. Preserve source-scoped names, capability/geometry invalidation and complete outputs; never retain draft entities.')
paragraph('docs/maintainers/performance.md','Dense 8x is not complete.', 'Extreme-density 8x remains unqualified. PF13 supersedes the assumed one-game-second stepping requirement; current elapsed measurements are not interchangeable with the historical fixed-step baseline. Continue regional/event-bound work, sensory indexing and history/render attribution without weakening meaningful effects or hiding debt.')
append('docs/maintainers/performance.md', '''## PF13 — Elapsed-time simulation

[Simulation time](../simulation-time.md) owns the engine contract; [base time](../worlds/base/time.md) owns bundled fidelity and [the boundary catalogue](simulation-boundaries.md) records future candidates. [Evidence](../verification/elapsed-simulation.md) separates executed diagnostics from unqualified scale and semantic coverage. This is not a second scheduler, physics engine or persistence program.

- [x] **PF13.1** Separate game-clock conversion, host integration opportunities, pose publication and device-paced rendering. Replace mandatory one-game-second iteration with bounded actual elapsed progress and retain unadvanced debt.
- [x] **PF13.2** Reconcile due start transitions, capture active status/native rates and working-action identity, integrate only their valid interval, then apply completion/status/perception outcomes. Preserve ordered commands, depletion/conservation and no retroactive work. Unsupported coupled/clamped families retain a documented fallback.
- [x] **PF13.3** Compose finite bounds for capacity/concern/needs, status comparisons/daily windows, work/supply, route/support waypoints, flight waits/landing/falling and conversation/commitment deadlines. Keep world policy outside universal engine assumptions; no model call or durable SDK object is introduced.
- [x] **PF13.4** Reuse conservative status applicability, immutable static-object exposure and unchanged episode membership. Preserve current-main physical contact and nonblocking memory pressure. Do not create duplicate owners when the speech branch is integrated.
- [x] **PF13.5** Fix start-boundary takeoff contact, numerical waypoint residue and pathological immediate blocked-flight retry through the existing saved wait. Five-game-second shared retry boundaries are revisitable bundled policy, not fair crowd arbitration. Keep underside/occupancy checks.
- [x] **PF13.6** Run actual finite-boundary, HTTP movement/pause/restart and 8x native/server stress observations. Record the dense contested-flight failure alongside near-target ordinary mixed-world results; no unlimited-capacity or physical-GPU claim.
- [x] **PF13.7** Read the current speech branch, preserve its ownership and post integration guidance on PR #3. Land/reconcile elapsed integration before combining its one-second snapshot batching; keep dB listener evidence and real-time captions. The combined branch is not yet qualified.
- [ ] **PF13.8** Qualify independent variable-partition/coupled-flow, simultaneous resource depletion, zero-time chains, threshold equality, fractional save/cursor handling and start/end event ordering. Cross-layer automated scenarios are SR27–SR31 in TODO; existing valid cases remain.
- [ ] **PF13.9** Replace global-minimum coupling only when a concrete region/participant scheduler can prove dependency and invalidation coverage. The contested-perch workload currently fails 8x. Profile local due queues, dirty sensing, blocked-landing occupancy wakeups and retained-history costs; do not solve it by moving fewer legitimate actors or changing clock speed.
- [ ] **PF13.10** Qualify richer swept perception/contact boundaries and unknown authored rate dependencies. Current one-metre sampling can miss short peeks/tangencies and relative motion; physical interaction admission is not proof of complete continuous awareness.
- [ ] **PF13.11** Run the joined hearing/elapsed stack with actual emissions, history, cognition scheduling and captions; qualify event-time snapshots, pause/load/source revocation and sustained frame/command tails. Caption time and rendering remain independent of acceleration.

Stop rule: prefer bounded elapsed families and explicit limitations over an unused generic event framework. A discovered natural deadline belongs in the catalogue with its invalidators and owner; it does not become implemented merely because it is listed.''')
replace('docs/maintainers/performance-profiling.md','Measured native one-second steps (default 180) and excluded warm-up steps (default 30). Use warmup 0 to include first encounters.','Measured native calls (default 180) and excluded warm-up calls (default 30). Use warmup 0 to include first encounters; actual progress can be smaller than the offered duration.')
replace('docs/maintainers/performance-profiling.md','Reports include setup/initial-freeze cost, native step percentiles','`intervalSeconds` controls offered game time per call (default 60); it is not a fixed tick or rendering rate.\n\nReports include setup/initial-freeze cost, native call percentiles')
replace('docs/maintainers/performance-profiling.md','Headroom divides measured native throughput','Headroom divides actual advanced game-seconds per wall second')
replace('docs/maintainers/performance-profiling.md','Reports distinguish requested steps, attempted steps, completed steps and actual `simulatedSeconds`.','Reports retain the existing requested/attempted/completed step fields as call counters and report actual `simulatedSeconds` and `intervalSeconds` separately.')
append('docs/maintainers/revisitable-policies.md', '''## RP03 — Global elapsed horizon and sampled discovery

**Current policy:** [Base time and observation fidelity](../worlds/base/time.md), under [simulation time](../simulation-time.md). The current finite integrator uses a global minimum boundary, bounded movement sampling, coupled-rule fallbacks and a shared blocked-flight retry deadline.

**Why revisit:** This is a small playable integration, not the final extreme-scale scheduler. Dense independent deadlines couple unrelated regions, and endpoint samples do not prove every transient contact/peek is detected.

**Review trigger:** A measured contested-perch/crowded-motion workload misses the clock target, brief contact becomes consequential gameplay, another world needs coupled rates, or a concrete region-local scheduler is ready. The current contested-flight evidence has already crossed the performance trigger; PF13.9 retains the next work.

**Decision authority:** Maintainer with spatial/perception/world owners. Mike decides material changes to discovery fidelity or game-time behavior. Do not silently relax collision, privacy, durability or meaningful events to meet a rate target.''')
append('docs/maintainers/TODO.md', '''## Elapsed-time cross-layer regression coverage

PF13 owns implementation; [runtime observations](../verification/elapsed-simulation.md) are not automated acceptance. No test files or assertion suites were added for this pass.

- [ ] **SR27 — Rates and interval boundaries:** exercise finite depletion/capacity/concern, strict/equal thresholds, daily windows, opposing/clamped rates and native/status coupling under varied partitions. Compare required effects and conservation independently, not only final scalars; newly active work receives no preceding time.
- [ ] **SR28 — Motion and local timers:** qualify fractional waypoints, support transitions, zero-length routes, numerical arrival residue, takeoff contact/underside rejection, terminal fall, perching and many blocked landings. Preserve wait remainders on load and verify shared retries do not become forced landing, duplicated events or a hidden fairness claim. Include deadline ordering and native wander RNG under alternate callback partitions.
- [ ] **SR29 — Host, persistence and overload:** actual time versus offered calls, pending navigation, speed/pause/suspension, near-zero residual time, late worker results, memory pressure versus true storage errors, fractional event times, named-save rewind and in-place upgrades. Count busy not-yet-admitted wall time; do not count a post-pause debt reset as capacity success.
- [ ] **SR30 — Joined speech/elapsed flow:** emissions immediately before/after movement, sleep, floor crossing, volume/policy change and source removal; immutable partial fragments and full-context privacy; shared sensing-phase batches; 1x/8x real-time caption life, hidden/pause/load and source revocation. Do not restore a per-game-second loop through branch conflict resolution.
- [ ] **SR31 — Sampling and rendering independence:** moving contacts/peeks smaller than current displacement bounds, opposing movers, zero-radius contact descriptors, interpolation through ramps/occluders, reliable speech/removal/revocation amid pose coalescing, and display-paced animation on named GPUs. Record allowed approximations rather than assert complete continuous sensing or 60 FPS from native throughput.''')
replace('docs/maintainers/speech-time-integration.md','`b72b683181f5a3147d603be619ad6dffb8efa988`, alongside the spatial branch based on `d67b99b21fff61580480d9740d4147db3aca713a`','`97668413082446e08d1e1fa5c3ee788067a1c7ef` (PR #3), alongside the spatial elapsed implementation merged with main `03105fed`')
replace('docs/maintainers/speech-time-integration.md','Its kernel/service still assumes one-game-second steps.','HE05 now batches bounded snapshots but explicitly retains one-game-second physics/sequence boundaries; that optimization must be reconciled with elapsed intervals, not layered on as a second cadence.')
append('docs/maintainers/speech-time-integration.md', '''## Coordination status

An integration note was posted on PR #3 (comment 5827327924), pointing out the obsolete 480-native-steps assumption, the shared helpers and the recommended merge order. The branch was inspected, not overwritten or merged by this task. Its PR body still contained older fresh-save instructions; current in-place preservation takes precedence. Recheck its tip before joining the branches and retain HE05's unqualified graphical/provider/scale gates.''')
replace('docs/maintainers/simulation-boundaries.md','Current finite displacement bound; smaller contact radii tighten it','Current finite displacement bound; smaller positive non-hearing detector radii can tighten it')
replace('docs/maintainers/simulation-boundaries.md','Integrated current corridor family; holding/fairness remains SW12','Integrated current corridor family and bounded shared retry wait; general holding alternatives/fairness remain SW12')
append('docs/maintainers/simulation-boundaries.md', '''## Observed global-deadline coupling

The current catalogue is consumed by one global minimum interval, not independent entity/region schedules. A crowded route/perch can require many small intervals and repeat work for unrelated actors. The actual 49-bird contested-perch scene fails 8x despite finite retry deadlines; PF13.9 owns the next isolation step.

| Scenario | Candidate boundary or invalidation | Status / owner |
| --- | --- | --- |
| Blocked route/perch retry | Existing saved wait reaches the next shared bundled retry boundary; current collision and occupancy are rechecked | Bounded implemented base policy, not fair crowd arbitration |
| Occupied destination becomes available | Changed occupancy/obstruction can wake only its registered waiters instead of periodic rechecks | Candidate; SW12/PF13.9; requires complete mutation and load invalidation |
| Independent local movers | Region or participant horizon until cross-region influence/contact; merge clocks only at actual dependencies | Candidate; PF13.9; one writer, event-time evidence and chronological consequences remain strict |
| Floating-point endpoint residue | Existing spatial/time tolerance resolves the same validated arrival/wait path, not repeated near-zero global work | Implemented finite numerical guard; SR28 retains partition/epsilon coverage |

A boundary becoming dense is a reason to revisit scheduling ownership, not proof that its effects can be discarded. Coalescing retries may add the explicitly accepted bounded wait; coalescing an actual collision, speech or required completion without a semantic rule is not equivalent.''')
after_title('README.md','''## Clock and frame rate

One real second represents one game minute at 1x; this is a clock conversion, not sixty world updates. Native simulation now integrates elapsed time to relevant boundaries, while rendering/camera input stay device-paced. See [simulation time](docs/simulation-time.md), [current observations and limits](docs/verification/elapsed-simulation.md), and the [running boundary catalogue](docs/maintainers/simulation-boundaries.md). Existing worlds evolve in place; no new save format or data directory is required by this change.''')
after_title('archive/05-project/implementation-status.md','''## Elapsed-time execution

Clock conversion no longer imposes one whole-world update per game second. Finite rates, native work, movement/fall/flight and relevant status/deadline boundaries use the [elapsed contract](../../docs/simulation-time.md); actual progress is charged to host debt. Shared status/static-exposure helpers and bounded blocked-flight retries are delivered. No dependency, save version or renderer frame cap was added. The global minimum interval and sampled discovery remain limitations: the contested-perch stress scene does not sustain 8x. [PF13](../../docs/maintainers/performance.md#pf13--elapsed-time-simulation) owns remaining region/coupled/acceptance work; [evidence](../../docs/verification/elapsed-simulation.md) records actual HTTP/native runs and the unmerged hearing coordination.''')
after_title('docs/maintainers/README.md','''## Elapsed-time work

[PF13](performance.md#pf13--elapsed-time-simulation) owns delivered elapsed integration and its remaining gates. [Simulation time](../simulation-time.md) is canonical; [base time](../worlds/base/time.md) owns bundled fidelity. The [running bounds catalogue](simulation-boundaries.md) collects implemented and future deadlines, while [speech integration](speech-time-integration.md) coordinates PR #3 without duplicating hearing requirements.''')
replace('docs/worlds/base/README.md','- [Body, senses and survival](survival.md)','- [Body, senses and survival](survival.md)\n- [Time and observation fidelity](time.md)')
after_title('docs/verification.md','Current elapsed-integration evidence: [actual boundary, HTTP/restart and stress observations](verification/elapsed-simulation.md). Prior fixed-step figures describe historical revisions; neither old tick counts nor a blocked call certify current throughput.')
after_title('docs/documentation-changelog.md','''## 2026-09-25 — Clock speed is not an update frequency

The accepted time conversion was clarified: one real second is one game minute, but no sixty-per-second global stepping requirement follows. [Simulation time](simulation-time.md) now owns elapsed-rate integration, start/end consequence ordering and separate rendering/publication clocks. The finite implementation advances to relevant mechanical/fidelity boundaries, reuses existing state, and preserves actual debt. [Base time](worlds/base/time.md) explicitly owns the current global horizon, sampled discovery and blocked-flight retry tradeoffs; [RP03](maintainers/revisitable-policies.md#rp03--global-elapsed-horizon-and-sampled-discovery) records their review triggers.

Main's requested agent guidance and newer contact/memory/save rules were preserved through a non-rewriting connector merge. The [catalogue](maintainers/simulation-boundaries.md) and [sound-branch handoff](maintainers/speech-time-integration.md) replace the assumption that every future bound must be designed now. PF13 marks finite delivery while retaining regional schedules, complex coupled rules and joint audio/graphics acceptance. [Executed evidence](verification/elapsed-simulation.md) includes a dense contested-flight failure; this is not a universal scale or graphics-performance claim.''')
paths=sorted(changed)
digest=hashlib.sha256(''.join(p+'\0'+hashlib.sha256((root/p).read_bytes()).hexdigest()+'\n' for p in paths).encode()).hexdigest()
if digest != '8e2dc2ec9545a22b7b5551bbf7b8a2314bc756cf46d745192eb8d24d6c5f55d0': raise RuntimeError('Review hash mismatch '+digest)
Path(os.environ['REVIEW_PATHS']).write_text(json.dumps(paths))
print('Authenticated',len(paths),'reviewed document updates')
