import fs from 'node:fs';
import * as D from '../packages/domain/src/index.ts';
import { perceptionFrameStats } from '../packages/domain/src/perception-frame.ts';
const cases=[];
let world=D.createWorld(73);D.migrateCognition(world);
for(const [id,e] of Object.entries(world.entities)) if(e.animal||e.spatial.flight) delete world.entities[id];
world=D.freezeWorld(D.advanceWorld(D.freezeWorld(world),1).world);
let step=D.advanceWorld(world,1);world=D.freezeWorld(step.world);
const stats=perceptionFrameStats(world);
if(!stats?.reused||stats.queried!==0||step.events.some(e=>e.type==='encounter')) throw Error('Stationary exposures not reused');
cases.push({name:'stationary-visibility-reuse',stats});
const object=world.visibleObjects[D.PLAYER_ID]?.[0];
if(!object)throw Error('Missing visible fixture object');
world=D.freezeWorld(D.updateWorld(world,d=>{d.entities[object].name='Changed visible fixture';}));
step=D.advanceWorld(world,1);world=D.freezeWorld(step.world);
const changes=step.events.filter(e=>e.type==='encounter'&&e.targetId===object);
if(!changes.length||changes.some(e=>e.scope!=='private'))throw Error('Stationary source feature change lost');
cases.push({name:'stationary-feature-change',privateEvents:changes.length});
const restored=D.freezeWorld(JSON.parse(JSON.stringify(world)));
D.validateWorldModules(restored);
step=D.advanceWorld(restored,1);
if(step.events.some(e=>e.type==='encounter'))throw Error('Restored exposure replay');
cases.push({name:'restore-rebaseline',schema:restored.schemaVersion,newAcquisitions:0});
// Move a visible source on a disposable candidate; native movement/perception remains authoritative.
let moved=D.freezeWorld(D.updateWorld(world,d=>{d.entities[object].position={x:1000,y:0,z:1000};}));
step=D.advanceWorld(moved,1);
if(step.world.visibleObjects[D.PLAYER_ID]?.includes(object))throw Error('Stationary observer retained moved hidden source');
cases.push({name:'source-motion-invalidates-stationary-observer',removed:true});
function compact(path){const r=JSON.parse(fs.readFileSync(path));return {steps:r.steps,totalMs:r.totalMs,p50Ms:r.p50Ms,p95Ms:r.p95Ms,maxMs:r.maxStepMs,counts:r.finalCounts,headroom:r.nativeHeadroomAtRequestedSpeed,hottest:r.hottestSelfMs?.slice(0,8)};}
const report={scope:'Ad hoc native exposure execution and matched-host profiles; no unit/browser suites or live models.',run:process.env.GITHUB_RUN_ID,node:process.version,paidModelCalls:0,cases,stress:{}};
for(const s of ['mixed','gems'])report.stress[s]={before:compact(`/tmp/epr-before-${s}.json`),after:compact(`/tmp/epr-after-${s}.json`)};
fs.writeFileSync('docs/verification/perception-exposure-reuse.json',JSON.stringify(report,null,2)+'\n');
console.log(JSON.stringify(report,null,2));
