from pathlib import Path
import re,json,subprocess,os
root=Path.cwd()
def edit(path,fn):
 p=root/path;p.write_text(fn(p.read_text()))
def section(path,heading,body):
 p=root/path;s=p.read_text();pattern=re.compile(r'^'+re.escape(heading)+r'\n.*?(?=^## |\Z)',re.M|re.S)
 replacement=heading+'\n\n'+body.strip()+'\n\n'
 if pattern.search(s):s=pattern.sub(lambda _:replacement,s,count=1)
 else:s=s.rstrip()+'\n\n'+replacement
 p.write_text(s)

# Keep the native executor generic while locating the bundled-world balance in its owner.
p=root/'packages/domain/src/follow.ts';s=p.read_text();m=re.search(r'export const FOLLOW_RULES = \{.*?\n\} as const;\n',s,re.S)
if not m:raise RuntimeError('Follow-rule ownership changed')
(root/'packages/domain/src/worlds/base/navigation.ts').write_text('/** Bundled-world follow tuning; the generic executor remains in domain/follow.ts.\n * docs/worlds/base/navigation.md#native-follow\n */\n'+m.group())
p.write_text(s[:m.start()]+"import { FOLLOW_RULES } from './worlds/base/navigation.js';\nexport { FOLLOW_RULES } from './worlds/base/navigation.js';\n"+s[m.end():])
# Missing fields in an old unresolved intention imply no target and no replace authority.
p=root/'apps/server/src/upgrade-world.ts';s=p.read_text();anchor='export function upgradeWorldState(world: WorldState): void {'
s=s.replace(anchor,anchor+'''
  // Earlier pending requests had no explicit target/mode scope. Preserve the request;
  // a stored alternative retains its mode, otherwise queueing grants no replace authority.
  for (const entity of Object.values(world.entities ?? {})) {
    const attempts = entity.actor?.agency?.attempts;
    if (!Array.isArray(attempts)) continue;
    for (const attempt of attempts) {
      if (!attempt || typeof attempt !== 'object') continue;
      if (!Object.hasOwn(attempt, 'targetEntityId')) attempt.targetEntityId = null;
      if (!Object.hasOwn(attempt, 'mode')) attempt.mode = attempt.alternative?.mode ?? 'enqueue';
    }
  }
''',1);p.write_text(s)

(root/'docs/worlds/base/navigation.md').write_text('''# Base-world navigation behavior

## Native follow

The bundled world supplies the follow tuning in `packages/domain/src/worlds/base/navigation.ts`: default separation 3 world units, accepted separation 1.5–12 units, a 0.75-unit hold/resume margin, and replanning after at least 1 unit of observed target displacement with a 4-game-second cadence. An empty route can require immediate route work. These are supplied-world choices, not universal rules for every authored reality.

The trusted executor owns movement, collision, current-perception checks and cancellation through the ordinary actor action lane. Follow currently means proximity to a visible living actor on supported ground. It ends honestly when perception, locomotion/actions capability, target viability or route support is lost. It does not implement stealth, scent, behind/beside formation, or sunset termination. Holding position remains ongoing work.

The root `follow.ts` re-export preserves current consumers of the single rule source; it is not another writable registry. A configurable installed navigation family is the extension trigger, not an unused loader now. See [capability contracts](../../action-capabilities.md), [spatial ownership](../../spatial-world.md), and [current implementation](../../architecture.md#native-follow-activity).
''')
p=root/'docs/worlds/base/README.md';p.write_text(p.read_text().rstrip()+'\n\n- [Navigation behavior](navigation.md) — bundled follow tuning and its current boundaries.\n')

# Active policy wins over pre-rebase per-feature save instructions; historical reports stay intact.
edit('README.md',lambda s:s.replace('Development saves support only the current format; autosaves are not implemented.', 'Development saves are upgraded in place where a safe small conversion is available; corruption remains an explicit error. Autosaves are not implemented.').replace('Schema 10 rejects older development saves without modifying them; select a fresh directory for either preset.', 'A separate directory selects a deliberately different demo world, not a required upgrade path; ordinary existing worlds evolve in place.').replace('unqualified `follow Ada`','unqualified following of a currently recognized or explicitly selected actor'))
edit('docs/action-capabilities.md',lambda s:s.replace('Follow the active no-legacy-development-save policy: incompatible saves fail explicitly. This feature adds no migration or compatibility reader.', 'Follow the [active development policy](save-and-load.md#active-development-policy): use small, identity-preserving in-place upgrades; reject malformed state rather than reset a world. Do not add per-feature versions or parallel legacy runtimes.').replace('The current development snapshot is schema 11 / `development-2026-09-24-actions2`; no legacy reader was added.', 'Current persistence follows the active in-place upgrade policy. Missing non-authoritative target/mode metadata is defaulted conservatively; existing alternative modes, commands, IDs and text remain unchanged.').replace('Changed target identity, revoked control, replaced plans or obsolete definitions invalidate only affected authority/components according to AG.', 'Changed target identity, revoked control, replaced plans or obsolete definitions invalidate only affected authority/components according to AG. Recognition-episode pins for delayed anonymous references remain an explicit integration requirement; a canonical entity ID is not a permanent recognition grant.'))
edit('docs/maintainers/action-capabilities.md',lambda s:s.replace('cold encounter/fan-out work; scale capacity evidence', 'remaining dense-state/persistence tails and population capacity qualification (PF-owned)').replace('Reject incompatible development saves explicitly. Do not add old-format migrations. Apply canonical active-definition policies rather than silently upgrading running calls.', 'Apply small identity-preserving upgrades under the active save/load policy. Reject unsafe or corrupt current state without reset. Definition activation must not silently retarget running calls.').replace('paused/completed', 'paused/completed'))

section('docs/architecture.md','## Native follow activity','''The `follow` command uses the existing physical action lane and movement owner. The single bundled-world tuning source is [base navigation](worlds/base/navigation.md#native-follow), re-exported through the native adapter for existing consumers. Following uses current visual evidence, bounded route updates and a hold/resume band. Losing perception, actions/locomotion capability, target viability or route support ends the activity honestly. Holding remains running. There is no hidden-position tracking, scent, stealth, sunset predicate or parallel movement writer.

Native and generated action labels use observer-specific descriptions. Short entity references, including nested navigation targets, resolve through the existing request-bound decoder. A global actor name is not available merely because the server knows it.''')
section('docs/architecture.md','## Private perception and evidence batches','''Visual acquisition records an observer-private `encounter` with observed modality and source/target provenance. Noticing something is not an outward act. Speech and physical effects retain their event-time audience rules. The fixed-position acquisition phase batches at most 128 new awareness entries through `mutateExperience`; this is an admission batch, not an observation cap. No evidence store or best-effort post-commit delivery was added.

Experience admission clones the caller's record and freezes that owned copy before insertion when the world is an immutable server-owned draft. Later owner edits still use drafts; external builder inputs are untouched. The former detached `current(rows)` evidence-freezing pass is removed. New events are sealed at native completion. Encounter-memory deduplication scans once per observer with new living contacts, not once per pair. The original patch-proven event-append lineage remains; a full-prefix-scan alternative was not retained.''')
section('docs/architecture.md','## Change-driven exposure and reaction intake','''The native post-movement frame captures current scalar entity fields without materializing the whole draft entity map and its action/status/agency subtrees. Immutable static objects reuse descriptors. Derived frames are keyed to exact committed snapshots; movement, removal, geometry, body/sense and perception-capability changes invalidate relevant results. Living and ordinary-object membership are reused independently: a moving person does not require rescanning unchanged static objects. Recomputed equal lists reuse the prior committed identity. An unchanged exposure with no outward-feature delta skips repeated acquisition sets and episode reconstruction.

The saved `perceptionFeatures` map is a coarse outward-feature baseline, not another knowledge store or generic sensory evaluator. Names of other actors use the knowledge owner's descriptions. Loss of perception clears live visibility and continuous recognition episodes; historical evidence remains. Moving sources still invalidate stationary observers. Main's installed status-effect semantics remain authoritative, including supported effects on non-actor objects; only inactive effects whose admission requires an actor skip inapplicable automatic checks.

`ActorWork` remains the coalesced scheduler. Repeated inspection of one frozen snapshot skips input reconstruction; diagnostic telemetry is not a cognition invalidator. At most 64 eligible schedule records are considered per pass with generation-aware acknowledgment. Main's current-evidence snapshot/coalescing behavior is preserved: old raw history is not a debt of queued model calls, and fixed cognition cooldowns/global thought intervals are not restored. `experiencesSince` remains available for ordered source access and maintenance without changing that policy. Raw sequence order is validated; safe existing arrays are stably ordered on upgrade without rewriting IDs or content. Lightweight per-mind signatures and source scans remain, rather than a fully mutation-fed regional index.

Startup and manual-save loading use the existing in-place upgrade path. Missing perception baselines and pending target/mode metadata receive conservative defaults; existing alternatives retain their mode. Malformed data is still rejected, and unrelated world identity, progress, accounting and evidence are not reset.''')
section('docs/architecture.md','## Cooperative native burst handling','''`advanceWorldWork` and synchronous `advanceWorld` share one deterministic transition. Checkpoints between actor work, status-effect groups, sensory candidates, acquisition groups and event sealing expose no candidate state. `native-step.ts` yields to the event loop after approximately eight milliseconds while `WorldService` keeps mutation ownership. Reads use the previous complete snapshot; commands cannot mutate a half-perceived world. No evidence is delayed into a later game tick or discarded to satisfy a budget.

Finalization, individual path queries, JSON encoding and database transactions can still block beyond that target. The real-server profiler records actual command latency, event-loop delays, simulated progress/debt and storage costs separately. Its dense SQLite case does not meet capacity or latency targets. A long-lived worker or asynchronous writer requires committed-only read isolation and measured benefit, not a second world authority. The existing long-callback suspension heuristic also remains a limitation during multi-second synchronous commits; counters expose excluded gaps, and nominal wall-time achieved speed must be reported rather than only admitted clock time.

The persistent `scripts/performance/profile-server.mjs` workload uses a disposable generated SQLite world, real native timer, SSE, and an independent client process with presence heartbeats. It bounds in-flight requests, reports rejections and skipped intervals, and disables paid providers. It does not qualify PostgreSQL, browser rendering, live cognition or long-session/multiplayer capacity.''')
edit('docs/architecture.md',lambda s:re.sub(r'The action slice advances current development saves to format 13 .*?earlier development worlds are rejected without mutation or migration\.', 'Action and perception state follow the active in-place upgrade policy; no per-feature world/save version or replacement data directory is required.',s,flags=re.S).replace('The retained architecture still has cold encounter/audience fan-out and bounded synchronous route preparation costs.', 'Remaining capacity limits include genuine dense acquisition/state construction, synchronous route preparation and persistence; private acquisition broadcasts have been removed.').replace('Changed queued work now retains actor cooldowns.', 'Changed queued work follows current actor eligibility.'))

section('docs/maintainers/performance.md','## Perception/evidence and burst delivery','''- [x] Remove private-acquisition audience amplification and batch through the existing experience owner; freeze owned record copies at insertion instead of materializing detached retained-history snapshots.
- [x] Read live perception scalars without whole-roster `current` copying; reuse living/object exposures independently and skip unchanged acquisition/episode reconstruction.
- [x] Preserve generic status-effect behavior while pruning inactive actor-only automatic conditions on non-actors; retain deterministic cooperative checkpoints through status phases.
- [x] Preserve main's current-evidence coalescing and diagnostic-independent ActorWork; do not restore fixed cognition cooldowns or a paid backlog-draining policy.
- [x] Record matched rebased-baseline/final native profiles plus real SQLite/HTTP/SSE workloads with a separate client and continuous presence. These are bounded observations, not population qualification; see [verification](../verification.md#rebased-action-and-perception-performance).
- [ ] Investigate the remaining dense first-commit cost through PF00/PF01: source/awareness construction, immutable state finalization, history encoding and SQLite transaction work must be attributed separately. Preserve individual evidence identity, privacy, revocation and atomicity. Do not yield a shared SQLite transaction to readers that could observe partial writes.
- [ ] Repeat full-server measurements with at least 1,000 successful commands, long mature history, 30-minute soaks, PostgreSQL, browser rendering and deterministic cognition/maintenance fixtures. Short 15-second phases have noisy tails and no live-model load.
- [ ] Address multi-second synchronous work interacting with the existing callback-gap suspension heuristic before claiming dense-world clock fidelity. Do not infer a new absence policy from CPU guesses or hide excluded time; remove blocking or qualify independent liveness evidence under PF10.
- [ ] Qualify the remaining per-mind/source signature walks and active-evidence array copy-on-write cost before introducing regional indexes or paged state. No witness dropping, changed perception rules, or guessed capacity promises.

### Residual capture and dense-scene gate

The earlier scalar-capture timeout investigation is superseded by the completed matched warm/cold capture measurements and preserved native digests. Source capture no longer calls `current` on the entire entity roster. The full-patch-elimination experiment was reverted: modest inconsistent benefit did not justify a retained-event prefix scan. Remaining dense-state/storage work stays open above; moving work to a worker alone does not reduce legitimate output volume.''')
# Replace the now-obsolete broad fan-out diagnosis, retaining the capacity qualification task.
edit('docs/maintainers/performance.md',lambda s:s.replace('Qualify and reduce first-exposure encounter/event/awareness fan-out before a population-scale claim. The existing mixed native scenario still exhibits a large cold maximum;', 'Qualify genuine dense acquisition and downstream storage before a population-scale claim. Accidental observer broadcast amplification is fixed;').replace('seal newly owned evidence at the final native phase','freeze owned evidence at admission').replace('Consume the ordered new-evidence tail; bound schedule reads and preserve newer dirty generations.', 'Preserve current-evidence coalescing; bound schedule reads and preserve newer dirty generations.'))
section('docs/performance.md','## Rebased acquisition and full-server measurement','''Keep native output correctness separate from implementation cost. Reuse unchanged observer/source relationships, freeze owned experience copies at insertion, and avoid whole-roster draft snapshots. Preserve generic status and knowledge semantics; never exchange actor-private evidence for a shared knowledge cache. Existing authoritative owners and deterministic transition order remain unchanged.

Measure the native kernel and actual server separately using the existing native profiler and the [bounded server workload](maintainers/performance-profiling.md#full-server-workload). Real-time debt, successful/rejected commands, SSE/projection, persistence, event-loop delay and excluded clock gaps all matter. Cold acquisition occurs after normal server bootstrap; native cold profiles remain a separate cache-start workload. Phase maxima labeled cumulative are not per-phase latency percentiles. Implementation, evidence and residual gates remain in [PF](maintainers/performance.md#perceptionevidence-and-burst-delivery) and [Verification](verification.md#rebased-action-and-perception-performance).''')
section('docs/maintainers/performance-profiling.md','## Full-server workload','''Run a generated, disposable scene through the real server timer, SQLite, SSE and a separate-process client:

```sh
pnpm run build
node --import tsx scripts/performance/profile-server.mjs scripts/performance/scenarios/mixed.json /tmp/openlegend-server-report.json 15 1,3,8
```

The output path must be new. The duration accepts 5–60 seconds per phase; supported requested speeds are 1, 3 and 8. Setup creates a private temporary data directory, populates a generated scenario with the timer disabled, then restarts the same world for actual timed measurement. User-save inputs are rejected. The profiler removes only its own temporary directory and disables all paid dispatch. It is not a PostgreSQL, browser, hosted-player or live-cognition benchmark.

A separate process reads state at 4 Hz, submits short move/cancel intentions at 2 Hz, consumes SSE, and sends presence heartbeats every 3 seconds. Each request lane has bounded concurrency. The report separates rejected requests, errors, request-scheduling lateness and skipped intervals from successful command latency; it cannot silently count an ungenerated request as success. SSE reports bytes/chunks, not browser render completion.

The first phase includes acquisition after ordinary bootstrap. Later phases reuse the evolving world and start at their recorded simulation time; do not describe these as independent identical fresh worlds. Before/after runs use the same host and scripted load, but wall-timed physics can diverge and small samples have noisy tails. Native fixed-step digest comparisons are separate evidence.

Report nominal elapsed-time achieved speed together with admitted/requested clock counters, pending debt and excluded gaps. Pending debt excludes elapsed wall time that an in-progress timer operation has not yet admitted. Existing >2-second callback-gap detection can misclassify long synchronous persistence as absence; the dense case does not qualify that boundary. Metric totals/counts are phase deltas, while `cumulativeMaxMs` is explicitly since startup. Keep initial presence-expiry runs separate from continuous-presence capacity evidence.

Long soaks, larger successful-command samples, genuine multiple players, slow consumers, PostgreSQL, browser rendering and no-network cognition/maintenance fixtures remain PF00/PF11 acceptance work.''')

# Preserve task IDs/checkboxes; update only obsolete acceptance assumptions.
edit('docs/maintainers/TODO.md',lambda s:s.replace('Do not add legacy migration tests while the [active development policy](../save-and-load.md#active-development-policy) is in force.', 'Cover safe in-place upgrades under the [active development policy](../save-and-load.md#active-development-policy); do not add reset-based fixtures or parallel legacy runtimes.').replace('do not add legacy-save fixtures.', 'include safe in-place field upgrades without introducing a parallel legacy runtime.').replace('cooldown eligibility before context work','current eligibility before context work').replace('sleep/need/interest/age/hour/day deadlines, cooldowns,','sleep/need/interest/age/hour/day deadlines,').replace('changed goals and interests, cooldown/restart,','changed goals and interests, restart,').replace('Dense first-arrival stress was interrupted before completion; add bounded execution and progress reporting before repeating it.', 'Bounded dense first-arrival runs now complete; retain the broader differential and scheduling acceptance cases.'))
section('docs/maintainers/TODO.md','## Rebased action/perception regression TODOs','''No unit or browser suites were written or run for this work. These are deferred regression cases, not claims of passing automated coverage. Runtime/profile evidence is in [Verification](../verification.md#rebased-action-and-perception-performance); PF/AG/EPR/SL retain implementation ownership.

- [ ] RPR01: compare cold and warm native transitions, ordered events/RNG and immutable inputs before/after scalar capture and category-local reuse. Include moving/removing/dead sources, observer motion, geometry edits, changed senses/status capabilities, asleep-to-awake transitions, and static objects beside moving people. Verify unchanged arrays/episodes retain identity only while valid.
- [ ] RPR02: validate freezing only owned experience copies, later owner text/edit/forget/obligation operations, duplicate rejection, ordering, missing sequences and large mature histories. Caller-owned mutable records must not freeze or alias. Preserve append/edit/delete/fork lineage and no cold-history prefix scan in the ordinary finalizer.
- [ ] RPR03: load existing main-world pending intents lacking target/mode and raw records with valid older ordering; preserve IDs, content, alternatives, world identity and accounting. Run twice for idempotence. Malformed present values must still fail, not be reset or guessed. Cover actual SQLite and PostgreSQL startup/manual-save paths.
- [ ] RPR04: unknown/global actor names must not leak into exact or generative action grounding or approval descriptions. Resolve nested short references through the common decoder. Perception loss clears continuous recognition without erasing knowledge/evidence; follow ends on lost perception/actions/locomotion capability.
- [ ] RPR05: preserve generic non-actor status effects while pruning only inactive effects whose own admission requires an actor. Compare synchronous/cooperative status-phase order and complete outcomes, including capability changes and cross-entity rates.
- [ ] RPR06: exercise independent full-server load generation, heartbeat expiry versus genuine overload, request identity/error classification, client crash/timeout, active SSE cleanup, bounded request lanes, cold setup and cumulative metric labels. Qualify long-run debt and the existing suspension heuristic under multi-second synchronous commits without changing offline-time policy silently.
- [ ] RPR07: qualify delayed pending/queued anonymous-target recognition across loss/reacquisition, world restore and source revocation when the shared reference/definition lifetime contract is reconciled. Canonical entity IDs must not become indefinite recognition permissions.
- [ ] RPR08: cover partial fulfillment through actual rebased player/NPC response admission (including note/name operations and exact no-AI paths), stored revision acceptance/rejection, changed work/manifest/status, and native output dependencies. Multi-command offered handles and general workflow result ports remain shared-contract work rather than silently selecting only a first step.''')

# Keep the focused EPR body; add a small delivery pointer without copying its acceptance matrix.
section('docs/maintainers/events-perception-and-reactions.md','## Rebased implementation boundary','''Private acquisition batching, scalar frame capture, category-local exposure reuse, unchanged-episode reuse and status-aware perception loss are implemented. The existing knowledge owner retains observer labels and continuous recognition; shared descriptors do not grant shared knowledge. Current-evidence coalescing follows main rather than an oldest-history dispatch backlog. These implementations do not complete EPR's richer sense semantics, regional mutation-fed indexes, reminders or full failure/scale matrix.

Measured kernel/server work and residual persistence gates belong to [PF](performance.md#perceptionevidence-and-burst-delivery); automated regression work remains in [TODO](TODO.md#rebased-actionperception-regression-todos). No new scheduler, sensory registry or inference loop was introduced.''')

# A compact report makes numerical comparisons inspectable without losing raw records.
native=json.loads((root/'docs/verification/action-perf-final-native.json').read_text())
server=json.loads((root/'docs/verification/action-server-summary.json').read_text())
compact={'scope':'Final rebased implementation summary; raw profile reports retain measurements and caveats. No unit/browser suites or live model calls.','main':'fc01e19b30060e6c7213b1c5405be13df209297e','rebasedBaseline':native['baseline'],'measurementRun':native['run'],'paidModelCalls':0,'native':{},'server':server['results']}
for name,row in native['cases'].items():
 compact['native'][name]={'requestedSpeed':1 if name.startswith('dense') else 3,'sameFinalDigest':row['sameFinalDigest']}
 for variant in ['before','after']:
  compact['native'][name][variant]={key:row[variant][key] for key in ['totalMs','p50Ms','p95Ms','maxStepMs','nativeHeadroomAtRequestedSpeed','finalCounts']}
(root/'docs/verification/action-perf-closeout.json').write_text(json.dumps(compact,indent=2)+'\n')
lines=['| Workload | Total before → after | p95 before → after | Maximum before → after | Equal final native digest |','| --- | ---: | ---: | ---: | --- |']
for name,row in compact['native'].items():
 a,b=row['before'],row['after'];lines.append(f"| {name} | {a['totalMs']:.0f} → {b['totalMs']:.0f} ms | {a['p95Ms']:.2f} → {b['p95Ms']:.2f} ms | {a['maxStepMs']:.0f} → {b['maxStepMs']:.0f} ms | {row['sameFinalDigest']} |")
body='''The feature was rebased onto `fc01e19` with completed work consolidated; the original history is retained at `backup/action-capabilities-before-main-20260924`. [Rebase record](verification/action-perf-rebase.json) records the actual operation and production build. Main's in-place upgrade, generic status effects, observer knowledge/short references, item actions and current-evidence/no-fixed-cooldown semantics are retained. `3be6601` is the rebased pre-optimization baseline, not the pre-main feature tip.

[Final native profiles](verification/action-perf-final-native.json) compare the same fixed-step scenarios on one runner. Cold runs use 180 advances; warm runs use 30 warm-up and 600 measured advances. These are one matched pair per case, not pooled tail qualification, and CPU-profiler overhead is included. Dense has 614 entities and was configured at 1× for this report; mixed/gems use 3× for the reported headroom denominator. Do not compare unnormalized headroom across these cases.

'''+ '\n'.join(lines)+'''

[Full-server summary](verification/action-server-summary.json) and its linked raw small/mixed/dense reports measure real timer scheduling, SQLite, SSE and independent-process command/state/presence load. Each speed phase is 15 seconds, with later phases continuing the same world. The small scene sustained requested 1×/3×/8×. Mixed throughput improved but did not sustain 3× or 8×; the dense cold case remains substantially below capacity. No storage error, memory-backlog stop or client exception was reported in the accepted runs. Command-tail changes are not uniformly improvements, and approximately 30 successful commands per phase do not establish p99 or soak behavior.

The first attempted server measurements omitted presence heartbeats and paused correctly after twelve seconds. They were replaced by continuous-presence measurements; no capacity claim uses that paused interval. The accepted dense report also records excluded long-callback time: it does not qualify the suspension detector under heavy synchronous persistence. Nominal wall-time achieved speed, not only admitted clock time, is reported.

[Integration execution](verification/action-perf-integration.json) covers observer-scoped names, status/perception/recognition loss, follow capability loss, identity-preserving raw-source upgrade and frozen-owned-evidence edits. Final build/static checks and the additional pending-intent upgrade exercise are recorded in the closeout review. No unit/browser suite was written or run; automated regression TODOs remain outstanding. Provider cost is zero and live-model judgment quality is not measured.

The [finalization experiment](verification/action-perf-finalization.json) was subsequently reverted: it preserved outcomes but gave no decisive broad benefit and introduced an event-prefix scan. The retained changes are owned-evidence freezing, removal of detached awareness snapshots, live scalar capture, independent object/living reuse and unchanged-acquisition fast paths. [Density](verification/action-perf-density.json) and [exposure](verification/action-perf-exposure.json) show intermediate pairs on their own hosts; their percentages must not be multiplied.

Remaining costs are real: dense source/awareness construction, immutable finalization, JSON/history encoding and synchronous SQLite transaction work, plus per-source/per-mind signatures. PF retains long soaks, PostgreSQL, browser/rendered movement, cognition fixtures, committed-only isolation for off-thread/async work and large-population qualification. Existing private evidence must not be discarded or made public to meet a latency target.'''
section('docs/verification.md','## Rebased action and perception performance',body)
section('archive/05-project/implementation-status.md','## Rebased action and perception integration','''Main's in-place upgrades, generic status effects, knowledge/short references and current-evidence cognition are integrated with action grounding, partial-fulfillment approval, native follow and private acquisition. The retained optimization reads current perception scalars, freezes owned evidence at admission, reuses independent exposure classes and skips unchanged acquisition/episode reconstruction. Status-phase checkpoints retain the single writer. Source names remain observer-scoped; perception/capability loss and old pending metadata are reconciled through their existing owners.

Production builds and bounded native/full-server execution are recorded in [Verification](../../docs/verification.md#rebased-action-and-perception-performance). Dense populations, long-session/postgreSQL/browser/live-cognition qualification and general invented workflow integration remain open. No new feature save version, second registry, scheduler or world writer was introduced.''')
section('docs/documentation-changelog.md','## Main rebase and measured acquisition follow-up','''Reconciled the action/perception branch with main's in-place save policy, generic status effects, observer knowledge and current-evidence scheduling. The old temporary-runner history is retained on a backup branch; active source uses the actual rebased implementation. Per-feature save-reset instructions are superseded by the active save owner, while historical measurement reports remain unchanged.

Added the reusable full-server profiler and recorded its continuous-presence correction, native warm/dense results and limits. The patch-removal experiment was not retained. Moved bundled follow tuning to its base-world source, retained the existing execution adapter and reserved invention-workflow reconciliation section, and added deferred regression coverage without running automated suites.''')

# Report remaining conflicting guidance for targeted review instead of blindly rewriting other owners.
keywords=re.compile(r'no-legacy|no legacy|rejects older|fresh (?:data )?director|adds no migration|schema (?:10|11|12|13)|cooldown',re.I)
audit={}
for path in ['README.md','docs/architecture.md','docs/action-capabilities.md','docs/maintainers/action-capabilities.md','docs/maintainers/TODO.md','docs/maintainers/events-perception-and-reactions.md','docs/maintainers/performance.md']:
 found=[{'line':i,'text':line[:1500]} for i,line in enumerate((root/path).read_text().splitlines(),1) if keywords.search(line)]
 if found:audit[path]=found
(root/'docs/verification/action-perf-doc-audit.json').write_text(json.dumps(audit,indent=2)+'\n')
print(json.dumps({'native':compact['native'],'documentationReviewCandidates':audit},indent=2))
