from pathlib import Path
import re,json

def edit(path,fn):
 p=Path(path);p.write_text(fn(p.read_text()).rstrip()+'\n')
def architecture(s):
 s=s.replace('Existing attempt/cooldown guards stay outside rewind.','Existing attempt identities, spending and external-operation guards stay outside rewind.')
 s=re.sub(r'\*\*2026-09-21:\*\* only the current development save format is supported, under the \[no-legacy policy\].*?not a requirement to maintain or extend\.', 'The [active development policy](save-and-load.md#active-development-policy) requires small in-place upgrades preserving identity, progress and accounting. Malformed state and integrity failures remain explicit errors; no reset or parallel legacy runtime is added.',s,flags=re.S)
 s=s.replace('use simulation-time deadlines plus durable wall-time cooldowns.', 'use explicit maintenance deadlines and current thought eligibility without fixed cognition cooldowns.')
 s=s.replace('thought signatures compute nearby visibility before readiness selection.', 'only eligible thought candidates revalidate committed exposure membership.')
 s=s.replace('Schema 11 and manual format `development-2026-09-24-actions2` persist intentions, queued/running work and deferred attempts. Startup/load validates their bounds and references and rejects incompatible development worlds without migration.', 'Intentions, queued/running work and deferred attempts persist through the existing save owner. Startup/load applies conservative identity-preserving upgrades and validates bounds and references; missing target/mode metadata does not reset the world or dispatch work.')
 return s
edit('docs/architecture.md',architecture)
edit('docs/maintainers/TODO.md',lambda s:s.replace('Old schema-8 fixture targets below have been superseded by schema 10; retain their behavioral cases, not an old-save conversion task.', 'Earlier fixture version labels are historical; use current constructors and safe in-place upgrade cases while retaining their behavioral coverage.').replace('for schema 10 and required authorship records','for current constructors and required authorship records').replace('for required origin stamps and schema 10','for required origin stamps and current constructors').replace('serial admission, same-actor cooldown, oldest-opportunity fairness','serial admission, immediate new-evidence eligibility, oldest-opportunity fairness').replace('Update current fixture constructors to schema 11 / `development-2026-09-24-actions2`; historical fixture-update entries above refer to earlier cutovers and do not require legacy migration.', 'Use current fixture constructors and the active in-place upgrade policy; do not require a per-feature save version or a reset to exercise these cases.').replace('more than 64 eligible minds, cooldown fairness','more than 64 eligible minds, eligibility fairness'))
edit('docs/maintainers/events-perception-and-reactions.md',lambda s:s.replace('Confirm the active no-legacy-support policy; use disposable current-format saves for experiments.', 'Confirm the active identity-preserving in-place upgrade policy; use disposable worlds for experiments.').replace('model gating, cooldown, and urgent-single-refresh behavior','model gating, unchanged-opportunity suppression, and urgent-single-refresh behavior').replace('existing Jev routing, cooldown, fairness and budgets','existing Jev routing, current eligibility, fairness and budgets'))
edit('docs/maintainers/performance.md',lambda s:s.replace('sleep/day boundaries, cooldowns, pause/speed changes','sleep/day boundaries, explicit maintenance deadlines, pause/speed changes'))
edit('docs/verification.md',lambda s:s.replace('Final build/static checks and the additional pending-intent upgrade exercise are recorded in the closeout review.', 'The [pending-intent upgrade exercise](verification/action-perf-pending-upgrade.json) preserves old unresolved requests without granting replacement authority, retains exact saved alternatives and rejects malformed present values. [Final static review](verification/action-perf-static-review.json) and the closeout record separate build/runtime observations from automated acceptance.'))
# Superseded grep candidates are working diagnostics, not another source of implementation status.
Path('docs/verification/action-perf-doc-audit.json').unlink(missing_ok=True)
for path in ['archive/05-project/implementation-status.md','docs/worlds/base/navigation.md']:
 edit(path,lambda s:s)
