import { writeFileSync } from 'node:fs';
import { createWorld, PLAYER_ID, NPC_ID, executeCommand, advanceWorld, commitActorResponse, updateWorld, deferAttempt, proposeActionRevision, confirmActionRevision } from '../packages/domain/src/index.ts';
import { groundActionAttempts } from '../apps/server/src/action-grounding.ts';
const report={scope:'Ad hoc native runtime exercise, no unit/browser suite and no live model calls.',run:process.env.GITHUB_RUN_ID,paidModelCalls:0,cases:[]};
const row=(name,value)=>{report.cases.push({name,...value});console.log(name,JSON.stringify(value));};
const action=(description,targetEntityId=null,mode='enqueue',localId='action')=>({localId,requiresAccepted:[],talk:null,think:null,goal:null,plan:null,act:{kind:'proposal',actionId:null,verb:null,description,targetEntityId,mode}});
let world=createWorld(73);
let nativeCalls=0;
const ports={judge:async()=>{nativeCalls++;throw new Error('Unexpected semantic call');},generate:async()=>{nativeCalls++;throw new Error('Unexpected semantic call');},record:async()=>{}};
const response={operations:[action('go to x=12, z=14')]};
const binding=await groundActionAttempts(world,PLAYER_ID,response,[],ports);
let transition=commitActorResponse(world,'review-move',PLAYER_ID,response,{},[PLAYER_ID,NPC_ID],world.entities[PLAYER_ID].actor.planGeneration,binding);
world=advanceWorld(transition.world,60).world;
row('exact-move',{outcome:transition.outcome,position:world.entities[PLAYER_ID].position,semanticCalls:nativeCalls,bindings:binding.map(b=>b.operationId)});
world=updateWorld(world,w=>{
 deferAttempt(w,PLAYER_ID,'target-one','Follow that person',NPC_ID,'enqueue');
 deferAttempt(w,PLAYER_ID,'target-two','Follow that person',PLAYER_ID,'enqueue');
 deferAttempt(w,PLAYER_ID,'mode-three','Follow that person',NPC_ID,'replace');
});
row('distinct-intent-slots',{attempts:world.entities[PLAYER_ID].actor.agency.attempts.map(a=>({id:a.id,target:a.targetEntityId,mode:a.mode}))});
world=createWorld(73);
const reportIntent={requested:'Follow Ada without being noticed',executableDescription:'Follow Ada at ordinary distance; no stealth.',verdict:'confirm',supported:['Follow Ada'],omitted:[{requirement:'without being noticed',reason:'No stealth mechanic'}],reason:'Explicit approval required.'};
world=updateWorld(world,w=>proposeActionRevision(w,PLAYER_ID,'held', [{id:'child',actorId:PLAYER_ID,type:'follow',targetId:NPC_ID}],reportIntent,'replace',w.entities[PLAYER_ID].actor.planGeneration,NPC_ID));
const next={operations:[{...action(null,null,'enqueue'),act:{kind:'invoke',actionId:null,verb:null,description:null,targetEntityId:null,mode:'enqueue',invocation:{family:'move',x:12,z:14,surfaceId:'terrain',targetEntityId:null,distance:null}}}]};
transition=commitActorResponse(world,'new-intent',PLAYER_ID,next,{},[PLAYER_ID,NPC_ID],world.entities[PLAYER_ID].actor.planGeneration,[]);world=transition.world;
const before=world.entities[PLAYER_ID].actor.agency.plan.id;
transition=executeCommand(world,{id:'old-approval',actorId:PLAYER_ID,type:'confirm-attempt',attemptId:'held'});
row('queued-intent-invalidates-old-replacement',{outcome:transition.outcome,planRetained:transition.world.entities[PLAYER_ID].actor.agency.plan.id===before});
const same={operations:[action('Follow this',NPC_ID,'enqueue','first'),action('Follow this',PLAYER_ID,'enqueue','second')]};
transition=commitActorResponse(createWorld(73),'operation-scope',PLAYER_ID,same,{},[PLAYER_ID,NPC_ID],0,[{operationId:'first',manifestRevision:world.moduleManifest.revision,description:'Follow this',commands:[{id:'scope-follow',actorId:PLAYER_ID,type:'follow',targetId:NPC_ID}],fulfillment:{...reportIntent,requested:'Follow this'}}]);
row('operation-binding-scope',{components:transition.world.responseReceipts['operation-scope'].components,attempts:transition.world.entities[PLAYER_ID].actor.agency.attempts.map(a=>({target:a.targetEntityId,status:a.status}))});
writeFileSync('docs/verification/action-review-core.json',JSON.stringify(report,null,2)+'\n');
